### ISSUE TITLE
this and that

### ISSUE THREAD

**Issue by justinmchase** [gamecook/RogueTS#1]
Not really an issue but since you didn't have comments on your blog I thought I would mention it here. You have this code in your project:
var that = this;
var _cb = function () { that.render(that); requestAnimationFrame(_cb); }
_cb(that);

I just wanted to mention that TypeScript has automatic "that = this" conversion for lambda expressions specifically for scenarios like this. For example the code above could be:

var _cb = () => { this.render(this); requestAnimationFrame(_cb); }
_cb(this);

Which will generate almost the exact same code you have above (except it creates a variable named _this instead of that).

**Comment by jessefreeman** [comment]
Thanks for the heads up. I was planning on doing a follow up on how I re-factored the code which is in a new branch and is much cleaner. I'll add this in.
